language: java
jdk:
  - oraclejdk8
  - oraclejdk7
cache:
  directories:
    - $HOME/.gradle
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ad76bd3a7bd257f0159c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
env:
  - DB=h2
  - DB=mysql
  - DB=postgres

before_script:
  - mysql -e 'create database deploydb;'
  - psql -c 'create database travis_ci_test;' -U postgres